version: "3"

services:
  database:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sweets
  cookie-eater:
    image: nginx
    ports:
      - "9005:80"
    volumes:
      - D:/projects/20posto/blog-angular-security/ws/who-ate-my-cookie/cookie-eater/app:/usr/share/nginx/html
